//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sammsar.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertising
    {
        public Advertising()
        {
            this.AdverView = new HashSet<AdverView>();
            this.Comment = new HashSet<Comment>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Mobile { get; set; }
        public bool CommentsEnabled { get; set; }
        public System.DateTime Date { get; set; }
        public int CountryID { get; set; }
        public bool Approve { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Item Item { get; set; }
        public virtual ICollection<AdverView> AdverView { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
