//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sammsar.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Advertising = new HashSet<Advertising>();
            this.Country1 = new HashSet<Country>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual ICollection<Advertising> Advertising { get; set; }
        public virtual ICollection<Country> Country1 { get; set; }
        public virtual Country Country2 { get; set; }
    }
}
