//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sammsar.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Describtion { get; set; }
        public int CategoryID { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
    
        public virtual Advertising Advertising { get; set; }
        public virtual Advertising Advertising1 { get; set; }
        public virtual Category Category { get; set; }
    }
}
