//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sammsar.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid ID { get; set; }
        public System.Guid SenderUserID { get; set; }
        public System.Guid ReciverUserID { get; set; }
        public string Message1 { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsSeen { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
