//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sammsar.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreference
    {
        public System.Guid ID { get; set; }
        public bool ShowEmail { get; set; }
        public bool ShowPhone { get; set; }
        public bool AllowMessage { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
